name: Java CI

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
    branches:
      - 'dev/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:8-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Upload to Maven
        run: ./gradlew publish --stacktrace
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
